### ISSUE TITLE
[TK-01] Revisar Archivo IEEE830

### ISSUE THREAD

**Issue by BrianGoldy** [Natalia24v/ProyectoISPCFullS#29]
Revisar y actualizar documento IEEE830

**Comment by Leytonale** [comment]
Actualizado hasta indice 2.1
[CitasYa-ieee830.pdf](https://github.com/Natalia24v/ProyectoISPCFullS/files/11292150/CitasYa-ieee830.pdf)

**Comment by Leytonale** [comment]
Documento Terminado 
[IEEE830.pdf](https://github.com/Natalia24v/ProyectoISPCFullS/files/11302832/IEEE830.pdf)
