### ISSUE TITLE
Agregar historias de usuarios

### ISSUE THREAD

**Issue by Natalia24v** [Natalia24v/ProyectoISPCFullS#5]
Plantear Historias de Usuarios y Tareas dependientes de las US para incorporarlas en el repositorio remoto GitHub. (Issues y Milestones) - Tener en cuenta la redacción adecuada para las US y nomenclatura, ej “#US01 Como usuario quiero ingresar al carrito para poder comprar”. (luego trasladarlas al Product Backlog del Project).

**Comment by nataliaruiz04** [comment]
Historias de usuarios y tareas#US01 Como administrador quiero crear una página web para reservas de citas en línea.
#US02 Como administrador quiero tener privilegios para realizar cambios en el sitio web.
#US03 Como administrador quiero tener privilegios para elegir que pueden ver y hacer los usuarios en la página web.
#US04 Como usuario quiero registrarme en el sitio para crear mi perfil.
#US05 Como usuario quiero hacer un comentario en el chat para consultar un tema específico.
#US06 Como usuario quiero recibir recomendaciones para conocer personas.
#TK01 Crear un archivo índex para el maquetado de la pagina
#TK02 Crear historias(US) y tareas (TK).
#TK03 Crear login para los usuarios.
#TK04 Integrar chat en el sitio web
#TK05 Crear base de datos.
